# Generated by Django 2.2.6 on 2019-10-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20191029_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosistema',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='articulosistema',
            name='sintomas',
        ),
        migrations.RemoveField(
            model_name='tratamientomedicamento',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='tratamientomedicamento',
            name='tratamiento',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='ArticuloSistema',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='Sintoma',
        ),
        migrations.DeleteModel(
            name='Tratamiento',
        ),
        migrations.DeleteModel(
            name='TratamientoMedicamento',
        ),
    ]
